
version: "3.9"

services:
  owl-dev:
    container_name: odoo-owl-dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - odoo-network

  # nginx:
  #   container_name: odoo-nginx-dev
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - owl-dev
  #   networks:
  #     - odoo-network

networks:
  odoo-network:
    name: odoo-network
    driver: bridge 