version: "3.8"

services:
  web:
    container_name: odoo-owl-dev
    build:
      context: .
      # dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - odoo-owl-network

networks:
  odoo-owl-network:
    name: odoo-owl-network
    driver: bridge
